dist: trusty
language: java
jdk:
- oraclejdk8
before_intall:
- export TZ=Brazil/East
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
    provider: heroku
    api_key:
        - secure: $SECURE_KEY
    app: $APP 